version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    command: npm start
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mongo